name: remove_diacritic
description: Package to replace diacritics and accents with equivalent characters.
version: 0.9.0
homepage: https://github.com/LeoCosta001/remove_diacritic

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
